// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/k8s/pod/container": {
            "get": {
                "description": "获取Pod内容器名",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "获取Pod内容器名",
                "operationId": "/api/k8s/pod/container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":\"\" }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pod/del": {
            "delete": {
                "description": "删除POD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "删除POD",
                "operationId": "/api/k8s/pod/del",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":\"\" }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pod/detail": {
            "get": {
                "description": "获取Pod详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "获取Pod详情",
                "operationId": "/api/k8s/pod/detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":v1.Pod }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pod/log": {
            "get": {
                "description": "获取容器日志",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "获取容器日志",
                "operationId": "/api/k8s/pod/log",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "容器名",
                        "name": "container_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":\"\" }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pod/numnp": {
            "get": {
                "description": "根据命名空间获取数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "根据命名空间获取数量",
                "operationId": "/api/k8s/pod/numnp",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":[]service.PodsNp }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pod/update": {
            "put": {
                "description": "更新POD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "更新POD",
                "operationId": "/api/k8s/pod/update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "更新内容",
                        "name": "content",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\":\"\" }",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        },
        "/api/k8s/pods": {
            "get": {
                "description": "获取pod列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pod"
                ],
                "summary": "获取pod列表",
                "operationId": "/api/k8s/pods",
                "parameters": [
                    {
                        "type": "string",
                        "description": "POD名称",
                        "name": "pod_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 200, msg=\"\",\"data\": service.PodsResp}",
                        "schema": {
                            "$ref": "#/definitions/middleware.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "middleware.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
